// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    IconLoadingBlue: typeof import('./components/icons/IconLoadingBlue.vue')['default']
    README: typeof import('./components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShowList: typeof import('./components/pages/home/ShowList/index.vue')['default']
    ShowTile: typeof import('./components/pages/home/ShowTile/index.vue')['default']
  }
}

export {}
